FROM ghcr.io/singularity-data/risingwave:v0.1.11
MAINTAINER Kiv Chen <qiwen@singularity-data.com>
USER root

ENV WORK_DIR /opt/recwave
RUN makedir -p $WORK_DIR

ADD * $WORK_DIR
WORKDIR $WORK_DIR
RUN ./build.sh
RUN ./recommender/run.sh
RUN cargo run -r --manifest-path ./simulator/Cargo.toml

# CMD ["./build.sh", "./build"]
