# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\"\x1f\n\rRecallRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\"0\n\x0eRecallResponse\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0e\n\x06itemid\x18\x02 \x03(\t\"J\n\x10GetRatingRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0e\n\x06itemid\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x65\x61ture_values\x18\x03 \x03(\x01\"C\n\x11GetRatingResponse\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0e\n\x06itemid\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\x32\x82\x01\n\x05Model\x12@\n\tGetRating\x12\x17.model.GetRatingRequest\x1a\x18.model.GetRatingResponse\"\x00\x12\x37\n\x06Recall\x12\x14.model.RecallRequest\x1a\x15.model.RecallResponse\"\x00\x62\x06proto3')



_RECALLREQUEST = DESCRIPTOR.message_types_by_name['RecallRequest']
_RECALLRESPONSE = DESCRIPTOR.message_types_by_name['RecallResponse']
_GETRATINGREQUEST = DESCRIPTOR.message_types_by_name['GetRatingRequest']
_GETRATINGRESPONSE = DESCRIPTOR.message_types_by_name['GetRatingResponse']
RecallRequest = _reflection.GeneratedProtocolMessageType('RecallRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECALLREQUEST,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:model.RecallRequest)
  })
_sym_db.RegisterMessage(RecallRequest)

RecallResponse = _reflection.GeneratedProtocolMessageType('RecallResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECALLRESPONSE,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:model.RecallResponse)
  })
_sym_db.RegisterMessage(RecallResponse)

GetRatingRequest = _reflection.GeneratedProtocolMessageType('GetRatingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETRATINGREQUEST,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:model.GetRatingRequest)
  })
_sym_db.RegisterMessage(GetRatingRequest)

GetRatingResponse = _reflection.GeneratedProtocolMessageType('GetRatingResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRATINGRESPONSE,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:model.GetRatingResponse)
  })
_sym_db.RegisterMessage(GetRatingResponse)

_MODEL = DESCRIPTOR.services_by_name['Model']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECALLREQUEST._serialized_start=22
  _RECALLREQUEST._serialized_end=53
  _RECALLRESPONSE._serialized_start=55
  _RECALLRESPONSE._serialized_end=103
  _GETRATINGREQUEST._serialized_start=105
  _GETRATINGREQUEST._serialized_end=179
  _GETRATINGRESPONSE._serialized_start=181
  _GETRATINGRESPONSE._serialized_end=248
  _MODEL._serialized_start=251
  _MODEL._serialized_end=381
# @@protoc_insertion_point(module_scope)
